export const information = [
  {
    title: "Over the",
    text: "Free market",
    text1: "Investor relations",
    text2: "Tendencies",
    text3: "Sustainability",
    text4: "Blog",
  },
  {
    title: "Over the",
    text: "Free market",
    text1: "Investor relations",
    text2: "Tendencies",
    text3: "Sustainability",
    text4: "Blog",
  },
  {
    title: "Over the",
    text: "Free market",
    text1: "Investor relations",
    text2: "Tendencies",
    text3: "Sustainability",
    text4: "Blog",
  },
  {
    title: "Over the",
    text: "Free market",
    text1: "Investor relations",
    text2: "Tendencies",
    text3: "Sustainability",
    text4: "Blog",
  },
  {
    title: "Over the",
    text: "Free market",
    text1: "Investor relations",
    text2: "Tendencies",
    text3: "Sustainability",
    text4: "Blog",
  },
  {
    title: "Over the",
    text: "Free market",
    text1: "Investor relations",
    text2: "Tendencies",
    text3: "Sustainability",
    text4: "Blog",
  },
];
