export const information = [
  {
    title: "Over the",
    text: "Free market",
    text1: "Investor relations",
    text2: "Tendencies",
    text3: "Sustainability",
    text4: "Blog",
  },
  {
    title: "Other websites",
    text: "Developers",
    text1: "Paid market",
    text2: "Submissions",
    text3: "Market Shops",
    text4: "Ads Market",
  },
  {
    title: "Contact",
    text: "Purchase",
    text1: "Sell",
    text2: "Problems solution",
    text3: "Segurança",
  },
  {
    title: "Social media",
    text: "Twitter",
    text1: "Instagram",
    text2: "YouTube",
  },
  {
    title: "My account",
    text: "Summary",
    text1: "Favorites",
    text2: "Sell",
  },
  {
    title: "Assinaturas",
    text: "Meli+",
    text1: "Disney+",
    text2: "Star+",
    text3: "Deezer Premium",
    text4: "Max",
    text5: "Paramount+",
  },
];
