export const productsDate = [
  {
    image: "/account.png",
    text: "Take advantage of offers to buy everything you want",
    value1: "$1009",
    value2: ["$7", "03", "16% OFF"],
    parcelation: "in 10x $77,90 interest-free",
    button: "free shipping",
  },
  {
    image: "/account.png",
    text: "Take advantage of offers to buy everything you want",
    value1: "$1009",
    value2: ["$7", "03", "16% OFF"],
    parcelation: "in 10x $77,90 interest-free",
    button: "free shipping",
  },
  {
    image: "/account.png",
    text: "Take advantage of offers to buy everything you want",
    value1: "$1009",
    value2: ["$7", "03", "16% OFF"],
    parcelation: "in 10x $77,90 interest-free",
    button: "free shipping  ",
  },
  {
    image: "/account.png",
    text: "Take advantage of offers to buy everything you want",
    value1: "$1009",
    value2: ["$7", "03", "16% OFF"],
    parcelation: "in 10x $77,90 interest-free",
    button: "free shipping",
  },
  {
    image: "/account.png",
    text: "Take advantage of offers to buy everything you want",
    value1: "$1009",
    value2: ["$7", "03", "16% OFF"],
    parcelation: "in 10x $77,90 interest-free",
    button: "free shipping",
  },
  {
    image: "/account.png",
    text: "Take advantage of offers to buy everything you want",
    value1: "$1009",
    value2: ["$7", "03", "16% OFF"],
    parcelation: "in 10x $77,90 interest-free",
    button: "free shipping",
  },
  {
    image: "/account.png",
    text: "Take advantage of offers to buy everything you want",
    value1: "$1009",
    value2: ["$7", "03", "16% OFF"],
    parcelation: "in 10x $77,90 interest-free",
    button: "free shipping",
  },
  {
    image: "/account.png",
    text: "Take advantage of offers to buy everything you want",
    value1: "$1009",
    value2: ["$7", "03", "16% OFF"],
    parcelation: "in 10x $77,90 interest-free",
    button: "free shipping",
  },
];
